// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArXE9bFG0nbtzIcc6ySRrFzrhCP03u5vk',
    appId: '1:1034547821132:web:183f21f4bafd6d7bd352e9',
    messagingSenderId: '1034547821132',
    projectId: 'ditonton-95ad5',
    authDomain: 'ditonton-95ad5.firebaseapp.com',
    storageBucket: 'ditonton-95ad5.appspot.com',
    measurementId: 'G-Y2YCKQM9S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ5wBK2CmYJOldQWTxEzEaoEtnBG6T17U',
    appId: '1:1034547821132:android:93e0bfa3be6eda1fd352e9',
    messagingSenderId: '1034547821132',
    projectId: 'ditonton-95ad5',
    storageBucket: 'ditonton-95ad5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLzyCQJ_Q4OZxRPckHLCF5yYIpDOFCOWg',
    appId: '1:1034547821132:ios:423e8723270b6ea3d352e9',
    messagingSenderId: '1034547821132',
    projectId: 'ditonton-95ad5',
    storageBucket: 'ditonton-95ad5.appspot.com',
    iosBundleId: 'com.example.ditonton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLzyCQJ_Q4OZxRPckHLCF5yYIpDOFCOWg',
    appId: '1:1034547821132:ios:e75e48e48f98f545d352e9',
    messagingSenderId: '1034547821132',
    projectId: 'ditonton-95ad5',
    storageBucket: 'ditonton-95ad5.appspot.com',
    iosBundleId: 'com.example.ditonton.RunnerTests',
  );
}
